### PR TITLE
feat: remove liquidity

### PR DESCRIPTION
**Pull request by luizstacio**
Remove liquidity enables sending the SWAY tokens to the contract and receiving back the provided tokens back.

Screen Shot 2022-04-23 at 5 31 03 PM

closes: #23

### CODE REVIEW

**Comment by SilentCicero** [comment]
"Remove" -> "Withdraw Liquidity" @luizstacio

**Comment by adlerjohn** [comment]
What is the rationale for "withdraw" rather than "remove" @SilentCicero?

**Comment by pixelsbyeryc** [comment]
“Withdraw” is mostly used to indicate that you’re taking something from somewhere and putting it in your “pocket” or “wallet”.

“Remove” doesn’t necessarily indicate that you’re pocketing that amount.

**Comment by adlerjohn** [comment]
FWIW, Uniswap seems to use "remove" from what I've been able to gather. My preference would be to use the same wording to start (confirm what the wording actually is), then bikeshed on changing in an issue.

**Comment by pixelsbyeryc** [comment]
@adlerjohn you’re right…

Binance uses:
- “redeem” for staking rewards
- “Add/Remove” for liquidity farming
- “Claim” to claim the rewards only


Here are some screenshots I took from my phone
E5BEB549-0AFA-4F27-8451-74A24C99CEBA
EF7AAAC5-886B-43EE-A201-F94A0895D922

**Review by AlicanC — APPROVED** [review]

**Pull request merged**
