### PR TITLE
feat: improve height controll to avoid content hidden and colissions

### PR DESCRIPTION
**Pull request by luizstacio**
On this PR we fixed the height control and also made some improvements on spacing and height control for mobile.

### CODE REVIEW

**Comment by SilentCicero** [comment]
I can report the preview deployment of this works on my end.

**Comment by SilentCicero** [comment]
Screen Shot 2022-06-23 at 10 15 56 PM

Fixed!

**Comment by SilentCicero** [comment]
Don't merge @luizstacio

**Comment by SilentCicero** [comment]
This messed up all the mobile formatting.

**Comment by luizstacio** [comment]
@SilentCicero these issues are related to old browser versions. I'm going to open another PR to fix it.

**Review by pedronauck — APPROVED** [review]

**Pull request merged**
