### PR TITLE
Create focus states for interactive UI elements and keyboard events for mouse-less navigation

### PR DESCRIPTION
**Pull request by pixelsbyeryc**
- Added focus states for all the buttons and UI elements that might become interactive
- Replaced the InvertButton icon for a more suggestive icon
- Added tabIndex for all clickable UI elements (for keyboard navigation)
- Added key events for clickable UI elements

### CODE REVIEW

**Comment by pixelsbyeryc** [comment]
A comment about key events: I wasn't sure whether to use `onKeyDown` or `onKeyPress`. So you'll see one or the other being used in different components.

The Button background color is also [failing all color contrast checks](https://colourcontrast.cc/58c09b/ffffff). I would update it, but I wasn't sure if FuelLabs has a guideline for color usage or not. 

It might be helpful to have some color scales available. Here's the [Radix UI Color Scales](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#teal) as a reference.

I'd be happy to help implement something like this. 😄

**Comment by luizstacio** [comment]
@pixelsbyeryc, thanks for the contribution.

Some points that can make even better your contributions;
- Use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) on your messages.
- Look into issues to help cover some missing points https://github.com/FuelLabs/swayswap/issues
- When doing some UI changes, it's really helpful to have an image or a video on the PR.

https://github.com/FuelLabs/swayswap/issues/54

**Comment by luizstacio** [comment]
> A comment about key events: I wasn't sure whether to use `onKeyDown` or `onKeyPress`. So you'll see one or the other being used in different components.
> 
> The Button background color is also [failing all color contrast checks](https://colourcontrast.cc/58c09b/ffffff). I would update it, but I wasn't sure if FuelLabs has a guideline for color usage or not.
> 
> It might be helpful to have some color scales available. Here's the [Radix UI Color Scales](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#teal) as a reference.
> 
> I'd be happy to help implement something like this. 😄

- `onKeyPress` is normally because it only triggers `down` and `up` after the press cycle.
- We don't have a scale of colors available yet, only base color. You can implement it if you want, it would be helpful.

**Comment by luizstacio** [comment]
@pixelsbyeryc some minor things;

- Rebase with `master`
- Add the styles to the new tab `remove`.
- When clicking it should not show as focus. To avoid this use `:focus-visible` instead of `:focus`.

**Comment by pixelsbyeryc** [comment]
@luizstacio 

> * Rebase with `master`
✅  Done.

> * When clicking it should not show as focus. To avoid this use `:focus-visible` instead of `:focus`.
Will be tackling this soon.

**Comment by pixelsbyeryc** [comment]
I'm testing a revamp to the design using [Radix UI Colors](https://www.radix-ui.com/docs/colors/palette-composition/the-scales).

**Here's the [Figma File I'm working with](https://www.figma.com/file/0oWykF2bYKj9hJ1XuDPaAP/SwaySwap?node-id=0%3A1).**

**Colors:**
- Accent colors: [`mintDark`](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#mint)
- Neutral colors: [`slateDark`](https://www.radix-ui.com/docs/colors/palette-composition/the-scales#slate)

**Font:** Inter (with a few caveats)

## Preview

### Entire UI (WIP)
Screen Shot 2022-04-29 at 3 10 24 AM

### Menu Item States
Screen Shot 2022-04-29 at 3 14 37 AM
 
### Menu Wallet Design (WIP)
Screen Shot 2022-04-29 at 3 14 57 AM

**Comment by adlerjohn** [comment]
> What's the best practice?

Try your best to make individual, atomic PRs for things that don't _need_ to be done together. Makes it easier (and faster!) to review and audit.

**Comment by pixelsbyeryc** [comment]
I've converted this into a Draft until I have updated the design + committed everything

**Comment by pedronauck** [comment]
I think this pull request is lit bit outdated since the new changes @luizstacio 🙄

**Comment by luizstacio** [comment]
Due to recent changes, I think this PR, will not be needed.

Thanks, @pixelsbyeryc for the contribution.

**Pull request closed without merging**
