### PR TITLE
refactor: use systems architecture

### PR DESCRIPTION
**Pull request by pedronauck**
✨ This pull request intends to change our architecture to a systems-based architecture, as we had in [other apps on fuels-ui](https://github.com/FuelLabs/fuels-ui/tree/master/apps)

### CODE REVIEW

**Comment by luizstacio** [comment]
I only found this one a bit different now;
Screen Shot 2022-06-02 at 10 07 28 PM

**Review by luizstacio — APPROVED** [review]
Nice refact., just found that one small thing with the button

**Review by luizstacio — CHANGES_REQUESTED** [review]
Just one small issue with the button

**Comment by luizstacio** [comment]
Screen Shot 2022-06-02 at 10 14 24 PM
I also found one issue with image using the `pnpm gh-preview`

**Comment by pedronauck** [comment]
all your requests are fixed @luizstacio :v:

**Review by luizstacio — APPROVED** [review]

**Pull request merged**
